development: &default
  adapter: postgresql
  encoding: unicode
  database: pizza_server_development
  pool: 5
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: pizza_server_test

production:
  <<: *default
  database: pizza_server_production
